/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include"ConComponent.h"
#include "recnum.h"
/* Header for class cn_hxc_imgrecognition_processActivity */

#ifndef _Included_cn_hxc_imgrecognition_processActivity
#define _Included_cn_hxc_imgrecognition_processActivity


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hxc_imgrecognition_processActivity
 * Method:    removeNoise
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL
Java_cn_hxc_imgrecognition_processActivity_removeNoise(JNIEnv *env, jobject instance, jintArray by_,
                                                       jint width, jint height);

/*
 * Class:     cn_hxc_imgrecognition_processActivity
 * Method:    callint
 * Signature: ([I)V
 */
//JNIEXPORT jint JNICALL Java_cn_hxc_imgrecognition_processActivity_callint
//  (JNIEnv *, jobject, jintArray, jint width, jint height,jstring num,jstring win2,jstring whi2,jint flag);
JNIEXPORT jint JNICALL Java_cn_hxc_imgrecognition_processActivity_callint(
        JNIEnv * env, jobject obj, jintArray by1_, jint width, jint height,
        jstring num_, jstring win2_, jstring whi2_,jint flag);

#ifdef __cplusplus
}
#endif
#endif
